Milestone 1
macbright/calculator pull request #1
Opened 2019-12-26 21:12 UTC by macbright

2019-12-26 21:22 UTC, macbright commented
i will fix the linter error later. can't fix it now cos i finished the whole project before requesting for the first review

2019-12-27 11:11 UTC, bolah2009 requested changes
Hi @macbright, nice job with the project setup.

Please let's use the lint configuration in this repo: https://github.com/microverseinc/linters-config/tree/master/react-redux also add a descriptive PR name and description, Note that you can edit your current PR name and description (See below). 

### Rename PR
  ![rename PR](https://user-images.githubusercontent.com/36057474/63838245-ec569f80-c974-11e9-93a9-83a4db5c259f.gif)
-----
### Update PR description
  ![update-PR-description-html](https://user-images.githubusercontent.com/36057474/64305800-6e078800-cf88-11e9-82f0-04e13fd6cb8d.gif)


#### :recycle:  Make these changes and submit another code review request. :+1: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2019-12-27 11:11 UTC, bolah2009 commented on .stickler.yml
> +        - 'js/index.js'
Let's use the content here instead: https://github.com/microverseinc/linters-config/blob/master/react-redux/.stickler.yml

2019-12-27 11:11 UTC, bolah2009 commented on eslint.config
> +}
Consider using this file and it's content instead: https://github.com/microverseinc/linters-config/blob/master/react-redux/.eslintrc.json

2019-12-27 19:02 UTC, bolah2009 approved these changes
It's a 👍🏾 from me!

### :heavy_check_mark: Approved!

Good luck with your next milestones. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-12-27 19:28 UTC, merged